{{- $fullName := include "chart.fullname" . -}}
{{- $name := "registry" -}}
{{- $data := dict "name" $name "Chart" .Chart "Release" .Release "Values" .Values -}}
{{- $imageCredentialsSecrets := list -}}
{{- with .Values.imageCredentials.existsSecrets }}
  {{- range . }}
    {{- $secretName := trim . -}}
    {{- if $secretName }}
      {{- $imageCredentialsSecrets = append $imageCredentialsSecrets $secretName -}}
    {{- end }}
  {{- end }}
{{- end }}
{{- if and .Values.imageCredentials.create (eq (len $imageCredentialsSecrets) 0) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}-{{ $name }}
  namespace: {{ include "chart.namespaceName" . }}
  labels:
    {{- include "chart.labels" $data | nindent 4 }}
  {{- if .Values.annotations }}
  annotations:
{{ toYaml .Values.annotations | indent 4 }}
  {{- end }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "imagePullSecret" . }}
{{- end }}
