// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	v1 "github.com/saremox/redis-operator/api/redisfailover/v1"
	service "github.com/saremox/redis-operator/operator/redisfailover/service"
	mock "github.com/stretchr/testify/mock"
)

// RedisFailoverHeal is an autogenerated mock type for the RedisFailoverHeal type
type RedisFailoverHeal struct {
	mock.Mock
}

// ApplyPassword provides a mock function with given fields: rFailover, password, previous
func (_m *RedisFailoverHeal) ApplyPassword(rFailover *v1.RedisFailover, password string, previous []string) (bool, error) {
	ret := _m.Called(rFailover, password, previous)

	if len(ret) == 0 {
		panic("no return value specified for ApplyPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) (bool, error)); ok {
		return rf(rFailover, password, previous)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) bool); ok {
		r0 = rf(rFailover, password, previous)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, []string) error); ok {
		r1 = rf(rFailover, password, previous)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ApplySentinelPassword provides a mock function with given fields: rFailover, password
func (_m *RedisFailoverHeal) ApplySentinelPassword(rFailover *v1.RedisFailover, password string) (bool, error) {
	ret := _m.Called(rFailover, password)

	if len(ret) == 0 {
		panic("no return value specified for ApplySentinelPassword")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string) (bool, error)); ok {
		return rf(rFailover, password)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string) bool); ok {
		r0 = rf(rFailover, password)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string) error); ok {
		r1 = rf(rFailover, password)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeletePod provides a mock function with given fields: podName, rFailover
func (_m *RedisFailoverHeal) DeletePod(podName string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(podName, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for DeletePod")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(podName, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// EnsureRedisMaxMemory provides a mock function with given fields: rFailover, master, redises
func (_m *RedisFailoverHeal) EnsureRedisMaxMemory(rFailover *v1.RedisFailover, master string, redises []string) (service.MaxMemoryResult, error) {
	ret := _m.Called(rFailover, master, redises)

	if len(ret) == 0 {
		panic("no return value specified for EnsureRedisMaxMemory")
	}

	var r0 service.MaxMemoryResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) (service.MaxMemoryResult, error)); ok {
		return rf(rFailover, master, redises)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, []string) service.MaxMemoryResult); ok {
		r0 = rf(rFailover, master, redises)
	} else {
		r0 = ret.Get(0).(service.MaxMemoryResult)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, []string) error); ok {
		r1 = rf(rFailover, master, redises)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// HandOverMaster provides a mock function with given fields: masterIP, targetIP, rFailover
func (_m *RedisFailoverHeal) HandOverMaster(masterIP string, targetIP string, rFailover *v1.RedisFailover) (service.HandoverResult, error) {
	ret := _m.Called(masterIP, targetIP, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for HandOverMaster")
	}

	var r0 service.HandoverResult
	var r1 error
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) (service.HandoverResult, error)); ok {
		return rf(masterIP, targetIP, rFailover)
	}
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) service.HandoverResult); ok {
		r0 = rf(masterIP, targetIP, rFailover)
	} else {
		r0 = ret.Get(0).(service.HandoverResult)
	}

	if rf, ok := ret.Get(1).(func(string, string, *v1.RedisFailover) error); ok {
		r1 = rf(masterIP, targetIP, rFailover)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MakeMaster provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) MakeMaster(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for MakeMaster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSentinelMonitor provides a mock function with given fields: ip, monitor, rFailover
func (_m *RedisFailoverHeal) NewSentinelMonitor(ip string, monitor string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, monitor, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for NewSentinelMonitor")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, monitor, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewSentinelMonitorWithPort provides a mock function with given fields: ip, monitor, port, rFailover
func (_m *RedisFailoverHeal) NewSentinelMonitorWithPort(ip string, monitor string, port string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, monitor, port, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for NewSentinelMonitorWithPort")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, monitor, port, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// PromoteBestReplica provides a mock function with given fields: newMasterIP, rFailover
func (_m *RedisFailoverHeal) PromoteBestReplica(newMasterIP string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(newMasterIP, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for PromoteBestReplica")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(newMasterIP, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ResizePodInPlace provides a mock function with given fields: rFailover, podName, updateRevision
func (_m *RedisFailoverHeal) ResizePodInPlace(rFailover *v1.RedisFailover, podName string, updateRevision string) (service.ResizeResult, error) {
	ret := _m.Called(rFailover, podName, updateRevision)

	if len(ret) == 0 {
		panic("no return value specified for ResizePodInPlace")
	}

	var r0 service.ResizeResult
	var r1 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) (service.ResizeResult, error)); ok {
		return rf(rFailover, podName, updateRevision)
	}
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover, string, string) service.ResizeResult); ok {
		r0 = rf(rFailover, podName, updateRevision)
	} else {
		r0 = ret.Get(0).(service.ResizeResult)
	}

	if rf, ok := ret.Get(1).(func(*v1.RedisFailover, string, string) error); ok {
		r1 = rf(rFailover, podName, updateRevision)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RestoreSentinel provides a mock function with given fields: ip
func (_m *RedisFailoverHeal) RestoreSentinel(ip string) error {
	ret := _m.Called(ip)

	if len(ret) == 0 {
		panic("no return value specified for RestoreSentinel")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(ip)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetExternalMasterOnAll provides a mock function with given fields: masterIP, masterPort, rFailover
func (_m *RedisFailoverHeal) SetExternalMasterOnAll(masterIP string, masterPort string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(masterIP, masterPort, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for SetExternalMasterOnAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, *v1.RedisFailover) error); ok {
		r0 = rf(masterIP, masterPort, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetMasterOnAll provides a mock function with given fields: masterIP, rFailover
func (_m *RedisFailoverHeal) SetMasterOnAll(masterIP string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(masterIP, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for SetMasterOnAll")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(masterIP, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetOldestAsMaster provides a mock function with given fields: rFailover
func (_m *RedisFailoverHeal) SetOldestAsMaster(rFailover *v1.RedisFailover) error {
	ret := _m.Called(rFailover)

	if len(ret) == 0 {
		panic("no return value specified for SetOldestAsMaster")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*v1.RedisFailover) error); ok {
		r0 = rf(rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetRedisCustomConfig provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) SetRedisCustomConfig(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for SetRedisCustomConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetSentinelCustomConfig provides a mock function with given fields: ip, rFailover
func (_m *RedisFailoverHeal) SetSentinelCustomConfig(ip string, rFailover *v1.RedisFailover) error {
	ret := _m.Called(ip, rFailover)

	if len(ret) == 0 {
		panic("no return value specified for SetSentinelCustomConfig")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, *v1.RedisFailover) error); ok {
		r0 = rf(ip, rFailover)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewRedisFailoverHeal creates a new instance of RedisFailoverHeal. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRedisFailoverHeal(t interface {
	mock.TestingT
	Cleanup(func())
}) *RedisFailoverHeal {
	mock := &RedisFailoverHeal{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
