apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover2
  labels:
    # The operator propagates these two labels.
    app.example.com/label1: value
    app.example.com/label2: value
    # The operator does not propagate this label, because no labelWhitelist regexp matches it.
    anotherlabel: value
spec:
  sentinel:
    enabled: true
    replicas: 3
    resources:
      requests:
        cpu: 100m
      limits:
        memory: 100Mi
  redis:
    replicas: 3
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 400m
        memory: 500Mi
  labelWhitelist:
  - ^app.example.com.*
