apiVersion: databases.spotahome.com/v1
kind: RedisFailover
metadata:
  name: redisfailover
spec:
  sentinel:
    enabled: true
    replicas: 3
  redis:
    replicas: 3
    affinity:
      podAntiAffinity:
        preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              # The labels that the operator sets on the Redis pods of this RedisFailover.
              labelSelector:
                matchLabels:
                  app.kubernetes.io/component: redis
                  app.kubernetes.io/name: redisfailover
                  app.kubernetes.io/part-of: redis-failover
              topologyKey: topology.kubernetes.io/zone
