// Code generated by mockery v2.53.7. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// Recorder is an autogenerated mock type for the Recorder type
type Recorder struct {
	mock.Mock
}

// DeleteCluster provides a mock function with given fields: namespace, name
func (_m *Recorder) DeleteCluster(namespace string, name string) {
	_m.Called(namespace, name)
}

// IncResourceEventQueued provides a mock function with given fields: ctx, controller, isRequeue
func (_m *Recorder) IncResourceEventQueued(ctx context.Context, controller string, isRequeue bool) {
	_m.Called(ctx, controller, isRequeue)
}

// ObserveResourceInQueueDuration provides a mock function with given fields: ctx, controller, queuedAt
func (_m *Recorder) ObserveResourceInQueueDuration(ctx context.Context, controller string, queuedAt time.Time) {
	_m.Called(ctx, controller, queuedAt)
}

// ObserveResourceProcessingDuration provides a mock function with given fields: ctx, controller, success, startProcessingAt
func (_m *Recorder) ObserveResourceProcessingDuration(ctx context.Context, controller string, success bool, startProcessingAt time.Time) {
	_m.Called(ctx, controller, success, startProcessingAt)
}

// RecordEnsureOperation provides a mock function with given fields: objectNamespace, objectName, objectKind, resourceName, status
func (_m *Recorder) RecordEnsureOperation(objectNamespace string, objectName string, objectKind string, resourceName string, status string) {
	_m.Called(objectNamespace, objectName, objectKind, resourceName, status)
}

// RecordK8sOperation provides a mock function with given fields: namespace, kind, name, operation, status, err
func (_m *Recorder) RecordK8sOperation(namespace string, kind string, name string, operation string, status string, err string) {
	_m.Called(namespace, kind, name, operation, status, err)
}

// RecordRedisCheck provides a mock function with given fields: namespace, resource, indicator, instance, status
func (_m *Recorder) RecordRedisCheck(namespace string, resource string, indicator string, instance string, status string) {
	_m.Called(namespace, resource, indicator, instance, status)
}

// RecordRedisOperation provides a mock function with given fields: kind, IP, operation, status, err
func (_m *Recorder) RecordRedisOperation(kind string, IP string, operation string, status string, err string) {
	_m.Called(kind, IP, operation, status, err)
}

// RecordSentinelCheck provides a mock function with given fields: namespace, resource, indicator, instance, status
func (_m *Recorder) RecordSentinelCheck(namespace string, resource string, indicator string, instance string, status string) {
	_m.Called(namespace, resource, indicator, instance, status)
}

// RegisterResourceQueueLengthFunc provides a mock function with given fields: controller, f
func (_m *Recorder) RegisterResourceQueueLengthFunc(controller string, f func(context.Context) int) error {
	ret := _m.Called(controller, f)

	if len(ret) == 0 {
		panic("no return value specified for RegisterResourceQueueLengthFunc")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(string, func(context.Context) int) error); ok {
		r0 = rf(controller, f)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetClusterError provides a mock function with given fields: namespace, name
func (_m *Recorder) SetClusterError(namespace string, name string) {
	_m.Called(namespace, name)
}

// SetClusterOK provides a mock function with given fields: namespace, name
func (_m *Recorder) SetClusterOK(namespace string, name string) {
	_m.Called(namespace, name)
}

// NewRecorder creates a new instance of Recorder. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRecorder(t interface {
	mock.TestingT
	Cleanup(func())
}) *Recorder {
	mock := &Recorder{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
