apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: redisoperator
rules:
  - apiGroups:
      - databases.spotahome.com
    resources:
      - redisfailovers
    verbs:
      - list
      - patch
      - watch
  - apiGroups:
      - databases.spotahome.com
    resources:
      - redisfailovers/finalizers
    verbs:
      - update
  - apiGroups:
      - databases.spotahome.com
    resources:
      - redisfailovers/status
    verbs:
      - get
      - patch
  - apiGroups:
      - discovery.k8s.io
    resources:
      - endpointslices
    verbs:
      - list
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - delete
      - get
      - list
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/resize
    verbs:
      - patch
  - apiGroups:
      - ""
    resources:
      - services
      - configmaps
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - update
  - apiGroups:
      - ""
    resources:
      - secrets
    # --watch-auth-secrets also needs list and watch.
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - controllerrevisions
    verbs:
      - get
  - apiGroups:
      - apps
    resources:
      - deployments
    verbs:
      - create
      - delete
      - get
      - update
  - apiGroups:
      - apps
    resources:
      - statefulsets
    verbs:
      - create
      - get
      - update
  - apiGroups:
      - policy
    resources:
      - poddisruptionbudgets
    verbs:
      - create
      - delete
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: redisoperator
  namespace: default
rules:
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - create
      - get
      - update
