apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-operator
spec:
  template:
    spec:
      containers:
        - name: redis-operator
          image: ghcr.io/saremox/redis-operator:v1.4.0
          ports:
            - name: metrics
              containerPort: 9710
              protocol: TCP
